"""drop subscription_level from users

Revision ID: 8991e85ac8c3
Revises: 43543ba33103
Create Date: 2025-10-30 02:52:19.556546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8991e85ac8c3'
down_revision: Union[str, None] = '43543ba33103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
